//
//  NewsInteractor.swift
//  VIP
//
//  Created by temptempest on 15.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol INewsInteractor{
	func fetchData(request: News.Request)
}

final class NewsInteractor: INewsInteractor {
	var presenter: INewsPresenter?
	var worker: NewsWorker

	init(presenter: INewsPresenter?, worker: NewsWorker) {
		self.presenter = presenter
		self.worker = worker
	}
	
	func fetchData(request: News.Request) {
		let response: News.Response = News.Response(result: worker.getNews())
		presenter?.present(response: response)
	}
}
