//
//  LoginInteractor.swift
//  VIP
//
//  Created by temptempest on 15.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ILoginInteractor {
	func login(request: LoginModels.Request)
}

final class LoginInteractor: ILoginInteractor {
	private var worker: LoginWorker
	private var presenter: ILoginPresenter?
	
	init(worker: LoginWorker, presenter: ILoginPresenter?) {
		self.worker = worker
		self.presenter = presenter
	}
	
	func login(request: LoginModels.Request) {
		let result = worker.login(login: request.login)
		let response = LoginModels.Response(succes: result)
		presenter?.present(response: response)
	}
}
